import { DASHBOARD, LOGO } from './assets.js';
import { dashboardData } from './reporting.js';
import { unqueuedCalls, transferNodeCounts, nodeOutcomeCounts } from './call-metadata.js';
const enc=new TextEncoder();
function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}
function redirect(path,headers={}){return new Response(null,{status:303,headers:{Location:path,'Cache-Control':'no-store',...headers}})}
function bytes(s){return Uint8Array.from(s.match(/../g),x=>parseInt(x,16))}
function hex(b){return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
async function key(env){return crypto.subtle.importKey('raw',bytes(env.TOKEN_ENCRYPTION_KEY),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function save(env,name,value){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(env),enc.encode(JSON.stringify(value)));await env.BUCKET.put(name,JSON.stringify({iv:hex(iv),data:hex(new Uint8Array(data))}))}
async function read(env,name){const o=await env.BUCKET.get(name);if(!o)return null;const v=await o.json();return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(v.iv)},await key(env),bytes(v.data))))}
function owner(request,env){return request.headers.get('oai-authenticated-user-email')?.toLowerCase()===env.OWNER_EMAIL.toLowerCase()}
function cookie(request,name){return request.headers.get('Cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)}
function page(content){return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OUCU | Webex connection</title><style>body{margin:0;background:#f2f7f8;color:#16383d;font:16px/1.5 'Segoe UI',Arial,sans-serif}main{max-width:620px;margin:60px auto;padding:32px;background:white;border:1px solid #deeaec;border-radius:12px}img{width:180px}h1{font-size:28px}p{color:#60777b}label{display:block;margin:20px 0 8px;font-weight:600}input{box-sizing:border-box;width:100%;padding:12px;border:1px solid #b6cdd1;border-radius:6px;font:inherit}button,a.button{display:inline-block;margin-top:20px;padding:12px 18px;border:0;border-radius:6px;background:#0b8295;color:white;font:inherit;text-decoration:none;cursor:pointer}a{color:#0b8295}.note{font-size:14px}.error{color:#a13727}@media(max-width:700px){main{margin:20px;padding:24px}}</style></head><body><main><img src="/logo.png" alt="OUCU Financial">${content}</main></body></html>`,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; style-src 'unsafe-inline'; img-src 'self'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com","Referrer-Policy":"same-origin"}})}
async function exchange(env,body){const r=await fetch('https://webexapis.com/v1/access_token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`Webex token request failed (${r.status}). Check the app secret and redirect URI.`);const t=await r.json();if(!t.access_token||!t.refresh_token)throw new Error('Webex did not return a complete token pair.');return{accessToken:t.access_token,refreshToken:t.refresh_token,expiresAt:Date.now()+Number(t.expires_in)*1000,refreshExpiresAt:Date.now()+Number(t.refresh_token_expires_in||0)*1000}}
async function access(env){let t=await read(env,'webex/tokens');if(!t)return null;if(t.expiresAt<Date.now()+120000){const config=await read(env,'webex/config');t=await exchange(env,{grant_type:'refresh_token',client_id:env.WEBEX_CLIENT_ID,client_secret:env.WEBEX_CLIENT_SECRET||config?.secret,refresh_token:t.refreshToken});await save(env,'webex/tokens',t)}return t.accessToken}
async function reportingCheck(env,token){const now=Date.now();const r=await fetch(`${env.WEBEX_API_BASE}/search?orgId=${encodeURIComponent(env.WEBEX_ORG_ID)}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query:'query($startTime: Long!, $endTime: Long!) { task(from: $startTime, to: $endTime, pagination: {cursor:"0"}) { tasks { id channelType } } }',variables:{startTime:now-86400000,endTime:now}}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`OUCU reporting check returned ${r.status}. Confirm the admin role, cjp:config_read scope, and contact center region.`);const v=await r.json();if(v.errors?.length)throw new Error('Webex accepted authorization but the reporting query needs adjustment.');return{checkedAt:new Date().toISOString(),recentTaskCount:v.data?.task?.tasks?.length??0,orgId:env.WEBEX_ORG_ID}}
export default {async fetch(request,env){const u=new URL(request.url);try{
 if(u.pathname==='/logo.png')return new Response(Uint8Array.from(atob(LOGO),c=>c.charCodeAt(0)),{headers:{'Content-Type':'image/png','Cache-Control':'public,max-age=86400'}});
 if(u.pathname==='/')return new Response(DASHBOARD,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'}});
 if(u.pathname==='/api/dashboard'&&request.method==='GET'){if(!request.headers.get('oai-authenticated-user-email'))return json({error:'Sign in required'},401);try{return json(await dashboardData(env,()=>access(env)))}catch(e){return json({error:e.message},503)}}
 if(u.pathname==='/api/transfer-nodes'&&request.method==='GET'){if(!request.headers.get('oai-authenticated-user-email'))return json({error:'Sign in required'},401);try{return json(transferNodeCounts(await unqueuedCalls(env,()=>access(env))))}catch(e){return json({error:'Transfer node counts are unavailable. An administrator can review Call metadata.'},503)}}
 if(u.pathname==='/api/node-outcomes'&&request.method==='GET'){if(!request.headers.get('oai-authenticated-user-email'))return json({error:'Sign in required'},401);try{return json(nodeOutcomeCounts(await unqueuedCalls(env,()=>access(env))))}catch(e){return json({error:'Node outcomes unavailable'},503)}}
 if(!owner(request,env))return json({error:'Only the dashboard owner can manage the Webex connection.'},403);
 if(!env.BUCKET||!env.TOKEN_ENCRYPTION_KEY)return page('<h1>Connection setup unavailable</h1><p>The secure storage configuration needs attention.</p><a href="/">Return to dashboard</a>');

 if(u.pathname==='/api/webex/unqueued-calls'||u.pathname==='/settings/calls'){
 let data=await unqueuedCalls(env,()=>access(env));
 const selectedNodes=(u.searchParams.get('nodes')||'').split(',').map(x=>x.trim()).filter(Boolean);
 if(selectedNodes.length)data={...data,calls:data.calls.filter(t=>selectedNodes.includes(nodeOutcomeCounts({calls:[t]}).rows[0]?.name))};
 if(u.pathname.startsWith('/api/')){const response=json(data);response.headers.set('Content-Disposition','attachment; filename="oucu-unqueued-calls.json"');return response}
 const esc=x=>String(x??'Not reported').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const time=x=>x?new Date(x).toLocaleString('en-US',{timeZone:'America/New_York'})+' ET':'Not reported';
 return page('<h1>Calls with no reported queue</h1><p>'+data.calls.length+' contacts since midnight Eastern. Latest node is based on activity start time; parallel activities may overlap. The dialed destination is not necessarily the transfer target.</p><a class="button" href="/api/webex/unqueued-calls'+(selectedNodes.length?'?nodes='+encodeURIComponent(selectedNodes.join(',')):'')+'">Download metadata JSON</a><p><a href="/">Return to dashboard</a></p>'+data.calls.map(t=>'<details style="margin:16px 0;border-top:1px solid #deeaec;padding:12px 0"><summary>'+esc(time(t.createdTime))+' · '+esc(t.terminationType)+' · '+esc(t.latestReportedNode?.activityName||t.flowActivityName)+' · '+(t.activityHistoryComplete?'Complete activity history':'Partial / unavailable activity history')+'</summary><p>Call ID: '+esc(t.id)+'<br>Caller: '+esc(t.origin)+'<br>Dialed number: '+esc(t.destination)+'<br>Entry point: '+esc(t.lastEntryPoint?.name)+'<br>Flow: '+esc(t.ivrScriptName)+'<br>Termination reason: '+esc(t.terminationReason)+'<br>Reported flow activity: '+esc(t.flowActivityName)+'<br>Flow activity sequence: '+esc(t.flowActivitySequence)+'</p><div style="overflow:auto"><table style="width:100%;font-size:13px;text-align:left"><thead><tr><th>Started</th><th>Node</th><th>Type</th><th>Event</th></tr></thead><tbody>'+t.activities.nodes.map(n=>'<tr><td>'+esc(time(n.createdTime))+'</td><td>'+esc(n.activityName)+'</td><td>'+esc(n.activityType)+'</td><td>'+esc(n.eventName)+'</td></tr>').join('')+'</tbody></table></div></details>').join(''));
 }

 if(u.pathname==='/api/webex/status'){const config=await read(env,'webex/config');const tokens=await read(env,'webex/tokens');const check=await read(env,'webex/reporting-check');return json({configured:!!config||!!env.WEBEX_CLIENT_SECRET,authorized:!!tokens,reportingVerified:!!check,checkedAt:check?.checkedAt,orgId:env.WEBEX_ORG_ID,metricsMode:'reporting'})}
 if(u.pathname==='/settings/webex'&&request.method==='GET'){const tokens=await read(env,'webex/tokens');return page(`<h1>Connect OUCU to Webex</h1><p>Authorize read access to OUCU’s Contact Center reporting.</p><p class="note">Organization: ${env.WEBEX_ORG_ID}<br>Region: United States</p>${tokens?'<p>Webex authorization saved. Use the reporting check to confirm OUCU access.</p><form method="post" action="/api/webex/check"><button>Check reporting access</button></form>':''}${env.WEBEX_CLIENT_SECRET?'<p class="note">Client Secret is configured in Render.</p><a class="button" href="/oauth/webex/start" target="_top">Authorize Webex</a>':'<form method="post" action="/oauth/webex/start"><label for="secret">Webex Client Secret</label><input type="password" name="secret" id="secret" required autocomplete="off" maxlength="512"><button>Save Client Secret</button></form>'}<p class="note">The secret and tokens are encrypted on the server. Authorization opens Webex; sign in with your OUCU administrator account.</p><p class="note">The dashboard reads today’s voice-contact reporting. Metrics without a verified source show Unavailable.</p><a href="/">Return to dashboard</a>`)}
 if(request.method==='POST'&&request.headers.get('Origin')!==env.APP_ORIGIN)return json({error:'Invalid request origin'},403);
 if(u.pathname==='/oauth/webex/start'&&(request.method==='POST'||(request.method==='GET'&&env.WEBEX_CLIENT_SECRET))){const form=request.method==='POST'?await request.formData():new FormData();const secret=env.WEBEX_CLIENT_SECRET||form.get('secret');if(typeof secret!=='string'||secret.length<8||secret.length>512)return json({error:'Enter a valid Client Secret'},400);await save(env,'webex/config',{secret});const state=hex(crypto.getRandomValues(new Uint8Array(32)));await save(env,`webex/state/${state}`,{expires:Date.now()+600000,user:request.headers.get('oai-authenticated-user-email')});const dest=new URL('https://webexapis.com/v1/authorize');dest.search=new URLSearchParams({client_id:env.WEBEX_CLIENT_ID,response_type:'code',redirect_uri:env.APP_ORIGIN+'/oauth/webex/callback',scope:'cjp:config_read',state}).toString();const stateCookie=`oucu_webex_state=${state}; Path=/oauth/webex; HttpOnly; Secure; SameSite=Lax; Max-Age=600`;if(request.method==='POST'){const response=page(`<h1>Continue to Webex</h1><p>Your Client Secret is saved. Sign in with your OUCU administrator account to authorize reporting.</p><a class="button" href="${dest.toString().replaceAll('&','&amp;')}" target="_top">Continue to Webex</a>`);response.headers.set('Set-Cookie',stateCookie);return response}return redirect(dest.toString(),{'Set-Cookie':stateCookie})}
 if(u.pathname==='/oauth/webex/callback'){const state=u.searchParams.get('state');if(!state||!/^[a-f0-9]{64}$/.test(state)||cookie(request,'oucu_webex_state')!==state)return json({error:'Authorization state is invalid. Restart the connection from settings.'},400);const pending=await read(env,`webex/state/${state}`);if(!pending||pending.expires<Date.now()||pending.user!==request.headers.get('oai-authenticated-user-email'))return json({error:'Authorization expired. Restart from settings.'},400);await env.BUCKET.delete(`webex/state/${state}`);if(u.searchParams.has('error')){const safe=value=>String(value||'').slice(0,1000).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');const error=safe(u.searchParams.get('error'));const description=safe(u.searchParams.get('error_description')||u.searchParams.get('errorDescription')||'Webex did not include an explanation.');return page(`<h1>Webex authorization was not completed</h1><p class="error"><strong>${error}</strong><br>${description}</p><p>Check that the Integration includes <strong>cjp:config_read</strong> and this exact redirect URI:</p><p class="note">${safe(env.APP_ORIGIN+'/oauth/webex/callback')}</p><p>Authorize using the administrator account inside OUCU’s organization.</p><a class="button" href="/settings/webex">Try again</a>`)}const code=u.searchParams.get('code');if(!code)return json({error:'Webex authorization code missing'},400);const config=await read(env,'webex/config');const t=await exchange(env,{grant_type:'authorization_code',client_id:env.WEBEX_CLIENT_ID,client_secret:env.WEBEX_CLIENT_SECRET||config?.secret,code,redirect_uri:env.APP_ORIGIN+'/oauth/webex/callback'});await save(env,'webex/tokens',t);return redirect('/settings/webex',{'Set-Cookie':'oucu_webex_state=; Path=/oauth/webex; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
 if(u.pathname==='/api/webex/check'&&request.method==='POST'){const token=await access(env);if(!token)return json({error:'Authorize Webex first'},409);const check=await reportingCheck(env,token);await save(env,'webex/reporting-check',check);return page(`<h1>OUCU reporting access confirmed</h1><p>Webex returned ${check.recentTaskCount} recent task records in the first response page.</p><p>The connection is working. Return to the dashboard to load today’s reporting data.</p><a class="button" href="/">Return to dashboard</a>`)}
 return json({error:'Not found'},404);
 }catch(e){console.error('Webex connection error',e.message);return page('<h1>Webex connection needs attention</h1><p class="error">'+String(e.message).replace(/[<>&"']/g,'')+'</p><a href="/settings/webex">Return to connection settings</a>')}}};

